### ISSUE TITLE
Python scripts of libscsicmd do not work with Python3

### ISSUE THREAD

**Issue by kalimalrazif** [baruch/diskscan#38]
I'm trying to make and get this error 
```
do          libscsicmd/include/ata_parse.h
do            ata_struct_2_h.py exists.
do            ata_identify.yaml exists.
  File "../structs/ata_struct_2_h.py", line 12
    """ % bit_params
      ^
SyntaxError: invalid syntax
do:         libscsicmd/include/ata_parse.h: got exit code 1
do:       arch/arch.o: got exit code 1
do:     arch/arch.a: got exit code 1
do:   diskscan: got exit code 1
do: all: got exit code 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

Using archlinux 
```
Linux echo1 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux
```

Seems to be an python version issue but I cant get it how to correct the issue

Thanks in advance

**Comment by baruch** [comment]
What is your python version? you can find it with ```python -V```

**Comment by baruch** [comment]
Make sure that whitespace was not modified in any way and that tabs are kept intact.

**Comment by kalimalrazif** [comment]
My python version.
```
python -V
Python 3.4.3
```
The code was just downloaded and then compiled, no modifications from me

**Comment by kalimalrazif** [comment]
My python version.
```
python -V
Python 3.4.3
```
The code was just downloaded and then compiled, no modifications from me

**Comment by baruch** [comment]
Can you try python 2.7?

**Comment by kalimalrazif** [comment]
Changing to python 2.7 on script make agagin and did not work :-( but I run the script from command line and work well, there are a central point were the python executable is set?

**Comment by kalimalrazif** [comment]
Searching found the script ata_parse.h.do call the others scripts via python change to python2 and works now the make stops on 
```
do          smartdb/smartdb_gen.c
do            smartdb_gen_c.py exists.
do            smartdb.xml exists.
  File "smartdb_gen_c.py", line 77
    print '#include "smartdb.h"'
                               ^
SyntaxError: Missing parentheses in call to 'print'
```
Gonna search for phyton again and change it

**Comment by kalimalrazif** [comment]
It works, change python to python2 on .do files works.... thanks :-D

**Comment by baruch** [comment]
I keep this issue as a note that libscsicmd needs to be fixed to work with Python3 as well, I'll see what it takes to make it work in both python versions.

Thanks for helping working out the issue!

**Comment by baruch** [comment]
Commit 83b968b07580606b0b133ad7fda439a0cd134721 fixes python3 compatibility issues.
