### ISSUE TITLE
Compilation problem with Documentation

### ISSUE THREAD

**Issue by jdn06** [baruch/diskscan#43]
I try to make a PKGBUILD for Archlinux, but I have two problems.
First one is an error about the sed script for Documentation:
```
ninja: error: build.ninja:93: unknown build rule 'script'
build Documentation/diskscan.1: script Documentation/diskscan.1.in
```
I tried to follow the instructions and used ninja 1.6.0, ctags 5.8 and python-yaml 3.11
My Python version is Python 3.5.0.

**Comment by baruch** [comment]
I'm using ninja 1.5.1 and it works. ninja 1.6 doesn't work though.

**Comment by baruch** [comment]
I'm planning to switch away from ninja to cmake soon (work in progress), you can use the following in configure to overcome the issue, it will break the build in 1.5.1 but will work for 1.6:


    rule script
      command = $script $in > $out
      description = SCRIPT $script $in

**Comment by jdn06** [comment]
Seems to work. Thank you very much.
I published the PKGBUILD: https://aur4.archlinux.org/packages/diskscan/
