### ISSUE TITLE
Complete compile dependencies in Debian/Ubuntu

### ISSUE THREAD

**Issue by pgmartinez** [baruch/diskscan#51]
You'll need some more packages...

apt-get install  cmake make libtinfo-dev libncurses5-dev ninja-build libtinfo-dev exuberant-ctags zlib1g-dev

**Comment by baruch** [comment]
You no longer need ninja-build (unless you want cmake to create ninja-build files instead of makefiles)

I'll check now what are the needed build files and will be sure to update them.

**Comment by baruch** [comment]
List of dependencies for debian package is: libncurses5-dev cmake zlib1g-dev python-yaml

It was sufficient for a build in a chroot, should be sufficient in other cases.

**Comment by baruch** [comment]
This is for git head (up and coming 0.18)

**Comment by baruch** [comment]
Update readme with the list in commit c046153118f624a053d921f3e68c384bdca518c1

**Comment by pgmartinez** [comment]
I recently compiled diskscan 0.16, 0.17 and 0.18pre in a fresh-installed Debian Jessie virtual machine, and I still needed to install the exuberant-ctags package.

**Comment by baruch** [comment]
If you take git head now, do you  still need it?

**Comment by pgmartinez** [comment]
OK, done. I uninstalled exuberant-ctags and recompiled the head version with no problems. You were right.

Thanks.
