### ISSUE TITLE
"do not attempt tp write if mounted"

### ISSUE THREAD

**Issue by Stoatwblr** [baruch/diskscan#57]
This is relatively safe if the disk is part of a redundant set. Scrubbing will find/fix the bad data spot later.

Adding a --yes-I-know-what-I-am-doing override would be useful.

**Comment by Stoatwblr** [comment]
Agreed. The bug's still there even with the latest commit.

The dro

**Comment by baruch** [comment]
Not sure what you are saying here

If you want to test a disk in a raid set, remove it from the raid and then test it and reinsert into raid if you deem it ok.

**Comment by baruch** [comment]
It is only safe if you then go on to validate your raid and even then the raid may not be smart enough to be able to recover, it is far safer to remove the drive from the raid and then check it.
