### ISSUE TITLE
"Failed to generate scan order" in Trisquel 7

### ISSUE THREAD

**Issue by ao-eu** [baruch/diskscan#59]
I'm a home user, not a professional.
Trisquel 7.
Diskscan 0.13-1 from Trisquel repo.

$ sudo diskscan /dev/sdc1
diskscan version unknown-1104c45

I: Validating path /dev/sdc1
I: Opened disk /dev/sdc1 sector size 512 num bytes 7797735424
I: Scanning disk /dev/sdc1
E: Failed to generate scan order

Thank you.

**Comment by baruch** [comment]
Can you please try to run it with -vvv for verbosity?
As in: ```sudo diskscan -vvv /dev/sdc1```

**Comment by ao-eu** [comment]
Here you are.

$ sudo diskscan -vvv /dev/sdc1
diskscan version unknown-1104c45

V: Verbosity set
V: High verbosity set
V: Very high verbosity set
I: Validating path /dev/sdc1
I: Opened disk /dev/sdc1 sector size 512 num bytes 7797735424
I: Scanning disk /dev/sdc1
V: Using buffer of size 65536
V: latency stride is 217571
E: Failed to generate scan order

**Comment by baruch** [comment]
I see that you are using an older version (roughly diskscan 0.13) can you please try the latest version?
There was at least one fix for such an issue since then.
