### ISSUE TITLE
12TB io error

### ISSUE THREAD

**Issue by alanjohn** [baruch/diskscan#61]
12TB drive connect to SAS2008 HBA CARD, firmware version:20.00.07.00, please check attach file for detail.
[sdb.log](https://github.com/baruch/diskscan/files/1434905/sdb.log)

**Comment by baruch** [comment]
any details?

**Comment by alanjohn** [comment]
[sdb.log](https://github.com/baruch/diskscan/files/1434877/sdb.log)

**Comment by alanjohn** [comment]
Hi, baruch

                 Sorry, I am answer later, I have uploaded sdb.log to you,
could you please check it?
Thanks
Alan

**Comment by baruch** [comment]
The error you are getting is 06/41/00 (Sense Key/ASC/ASCQ), translates to Unit Attention Data Path Failure. Since this is a SATA drive this error code is likely generated by the kernel and not coming from the drive directly. It may be a translation of an error the OS sees while communicating to the drive.

I'd check the cabling and connectors to the drive, try to move it to another connection and see if the issue persists. This isn't a media problem but it will still cause problems if it persists.

**Comment by alanjohn** [comment]
Hi Even

             I appreciate you  to spend time to support me, I will try
connect to on board SATA port today, and let you know if working.

Thanks
Alan

**Comment by alanjohn** [comment]
Hi Even

            I connected to on board SATA is working, if connect to SAS2008
failed, l also updated latest FW and driver. I think is HBA card issue. By
the way,  can I use diskscan test hard drive latency? Or any good idea to
test hard drive latency .

Thanks
Alan

**Comment by baruch** [comment]
How is it connected now? Is it to a SAS port?

**Comment by baruch** [comment]
diskscan is useful for hard disk latency in a sequential 1 queue depth mode only. It is not really intended as a full blown latency test. There are other tools for that like fio that allow you to setup more complex scenarios and different block sizes.

The latency test in diskscan is mostly intended to flush out bad media blocks or those getting pretty unreadable.

**Comment by alanjohn** [comment]
Hi Even

            SATA Port not SAS .

Thanks
Alan

**Comment by alanjohn** [comment]
Hi Even,

            How to use diskscan to test hard drive latency, or if I use fio
to test latency and how to setup config file for each hard drive . Could
you please give me idea. I appreciate you again.

Thanks
Alan

**Comment by baruch** [comment]
When you run diskscan it shows you the latency data, on the screen itself it should show a text graph of the latencies with min/median/max. That's all there is to it.

As for fio, I never used it myself so I can't help you there.

**Comment by alanjohn** [comment]
Hi Even,


             I check hard drive logs file, I saw latency, but scan
different sectors and different latency, how to know which hard drive is
better.
Have nice weekend! Even

Thanks
Alan

**Comment by baruch** [comment]
When you run diskscan it shows you the latency data, on the screen itself it should show a text graph of the latencies with min/median/max. That's all there is to it.

As for fio, I never used it myself so I can't help you there.

**Comment by baruch** [comment]
That would be a judgement call, there is no real good way to know which one is better. It also depends on your definition of "better".

**Comment by alanjohn** [comment]
Hi Even, 
             Got it! I appreciate you again. 


Thanks Alan 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Baruch Even <notifications@github.com> Date: 11/4/17  2:45 PM  (GMT-05:00) To: baruch/diskscan <diskscan@noreply.github.com> Cc: alanjohn <alanzhen1968@gmail.com>, Author <author@noreply.github.com> Subject: Re: [baruch/diskscan] 12TB io error (#61) 
That would be a judgement call, there is no real good way to know which one is better. It also depends on your definition of "better".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/baruch/diskscan","title":"baruch/diskscan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/baruch/diskscan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@baruch in #61: That would be a judgement call, there is no real good way to know which one is better. It also depends on your definition of \"better\"."}],"action":{"name":"View Issue","url":"https://github.com/baruch/diskscan/issues/61#issuecomment-341920629"}}}
