### ISSUE TITLE
Badblocks isnt entirely useless on SMART drives

### ISSUE THREAD

**Issue by fennectech** [baruch/diskscan#66]
A badblocks -nsv pass will prod a properly functioning drive to find and remap any pending or unnoticed bad sectors.    If repeated read write passes don't result in bad sectors actually being remapped the drive has larger issues that warrant a replacement imediately

**Comment by baruch** [comment]
Any self-respecting SSD already has an internal Background Media Scan and will reallocate bad sectors on its own.
The problem left is to know that this happens and to know that the drive is having problems, and SMART is only lightly useful for this as it will only help when things are already in a pretty dire state.

diskscan is far more useful on HDDs than on SSDs as well for the same reasons. Though a bad SSD will also show up in far higher latencies compared to other SSDs of the same model, but most people do not have that many SSDs to be able to compare and contrast them.

**Comment by fennectech** [comment]
I’m talking about HDDs.  Ive been using badblocks to test and clean up any pending bad blocks.
