### ISSUE TITLE
Homepage is down

### ISSUE THREAD

**Issue by meator** [baruch/diskscan#67]
Hello, the projects [main page](blog.disksurvey.org/proj/diskscan/) listed in the About section isn't accessible. Is this temporary or should the GitHub page be used as the main page?

**Comment by baruch** [comment]
My main site is down for a long time and I need to create a page for diskscan on github itself.

**Comment by baruch** [comment]
I'm not sure I'll create a new home page for now, closing this issue.

**Comment by baruch** [comment]
I removed the link to the old homepage, that server is long gone.
